name: auto_build

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: subosito/flutter-action@v2.1.0
        with:
            channel: 'stable'
      - run: sudo apt install build-essential ninja-build clang cmake pkg-config libgtk-3-dev liblzma-dev
      - run: flutter pub get
      - run: pub run flutter_launcher_icons:main
      - name: Build linux
        run: flutter build linux
      - name: Build android
        run: flutter build apk
      - name: Build web
        run: flutter build web --base-href="/fluttervcc/" --web-renderer=canvaskit --no-web-resources-cdn
      - run: tar cfz linux.tar.gz build/linux/x64/release/
      - uses: actions/upload-artifact@master
        with:
          name: fluttervcc_amd64_linux.tar.gz
          path: linux.tar.gz
      - uses: actions/upload-artifact@master
        with:
          name: fluttervcc.apk
          path: build/app/outputs/apk/release/app-release.apk
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
